# Example dataset configuration for run_schema_agent.py
#
# Each entry should have:
#   - index_name: Name of the log index (used in output filename)
#   - log_file: Path to JSONL file containing log samples

- index_name: complete_endpoint
  log_file: log_samples/Amsys/analysis/complete_endpoint_data_amsys_flattened.jsonl

- index_name: endpoint
  log_file: log_samples/Amsys/analysis/endpoint_data_amsys_flattened.jsonl

- index_name: network
  log_file: log_samples/Amsys/analysis/network_data_amsys_flattened.jsonl


